FROM php:8.2-apache

# Instala extensiones necesarias
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Copia archivos del proyecto
COPY . /var/www/html/

# Expone el puerto usado por Apache
EXPOSE 80
